# Generated by Django 3.2.8 on 2022-05-30 18:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='День Рождения'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='users/unknow.png', null=True, upload_to='users_photo', verbose_name='Фотография'),
        ),
    ]
