# Generated by Django 3.2.7 on 2021-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmusersinfo',
            options={'verbose_name': 'Информация о фильме', 'verbose_name_plural': 'Информация о фильмах'},
        ),
        migrations.AddField(
            model_name='filmusersinfo',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публичный список'),
        ),
    ]
