# Generated by Django 3.2.7 on 2021-10-06 21:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='about_user',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(blank=True, default='2002-09-20', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2001, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='День Рождения'),
        ),
    ]
