# Generated by Django 3.2.7 on 2021-10-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmusersinfo',
            name='is_published',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публичный список'),
        ),
    ]
