# Generated by Django 3.2.7 on 2021-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211007_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmusersinfo',
            name='series',
            field=models.CharField(blank=True, choices=[('Planned', 'Запланировано'), ('Viewed', 'Прсомотрено'), ('Abandoned', 'Брошено'), ('None', 'Не в списке')], default=None, max_length=9, null=True, verbose_name='Список'),
        ),
    ]
