# Generated by Django 3.2.7 on 2022-04-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211011_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default='users/unknow.png', upload_to='users_photo', verbose_name='Фотография'),
        ),
    ]
