# Generated by Django 3.2.8 on 2022-05-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(related_name='country', to='main.Country', verbose_name='страны'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='main.Genre', verbose_name='жанры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='films', to='main.series', verbose_name='Серия фильмов'),
        ),
    ]
