# Generated by Django 3.2.8 on 2022-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220529_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(related_name='films', to='main.Country', verbose_name='страны'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='main.Genre', verbose_name='жанры'),
        ),
    ]
