# Generated by Django 3.2.8 on 2022-05-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold')], max_length=10)),
            ],
            options={
                'verbose_name': 'Тип подписки',
                'verbose_name_plural': 'Типы подписок',
                'permissions': (('color_username', 'Have a color username'), ('can_create_public_film_room', 'Can create public film rooms'), ('can_create_private_film_room', 'Can create private film rooms'), ('can_watch_movies_in_advance', 'Can watch movies in advance')),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('expires_at', models.DateField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_type', to='subscriptions.subscriptiontype')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
