# Generated by Django 3.2.8 on 2022-05-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='payment_method',
            field=models.CharField(choices=[('usd', 'USD'), ('grn', 'Grivna'), ('euro', 'Euro')], max_length=7),
        ),
    ]
